### ISSUE TITLE
Release ZIPs not including trident-ext-src package?

### ISSUE THREAD

**Issue by teward** [tridentli/trident#71]
I think the Release ZIP files which contain the packages don't currently include ext-src packages, based on the last download I did today; did CI / automated creation of this ZIP skip it?

**Comment by bapril** [comment]
trident-ext-src is only required if you want to build. It's also 34MB. It is listed in the release files (https://github.com/tridentli/trident/releases/download/v1.4.5/trident-ext-src_0.1.5_all.deb), but I left it out of the zip so that folks who only want to install it can move a smaller file around.

**Comment by teward** [comment]
That explains it.  Thanks.
